---
title: CV
excerpt: My current CV
date: 2024-07-13
published-title: CV last updated
---

```{=html}
<div class="text-center">
    <a class="cv-download" href="/_assets/documents/cv.pdf" target="_blank">
        Download a PDF
    </a>
</div>
```

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>

## Education  
- Ph.D in Mathematics, Florida State University; Florida, USA 2026 (expected)
- M.S. in Mathematics, Youngstown State University; Ohio, USA 2020
- M.S. in Applied Mathematics, University of Dhaka; Dhaka, Bangladesh 2016
- B.S. in Mathematics, University of Dhaka; Dhaka, Bangladesh 2014


## Work experience  

* Graduate Teaching Assistant (Fall 2021- To Date)
  * Florida State University
  * Duties includes: Teaching, Proctoring, and Grading
  * Teaching Supervisor: Penelope Kirby, Ph.D

* Graduate Teaching Assistant (Fall 2018 - Spring 2020)
  * Youngstown State University University
  * Duties included: Teaching, Proctoring, and Grading
  * Supervisor: G. Jay Kerns, Ph.D

* Assistant Vice President (September 2017 - July 2018)
  * Delta Life Insurance Company Ltd. Dhaka, Bangladesh
  * Duties included: Calculated all types of claims (death, surrender, and maturity) using excel spreadsheets. 
  * Processed approximately 500 claims each week and submitted corresponding statistical reports to the higher authority. 
  * Worked in a team to develop a new short-term endowment assurance product which played an important role to increase the company's new business. 
  * Refurbished a without risk endowment product which was out of the sale. Priced insurance premiums based on different risk factors for bigger clients which impacted our life fund significantly. 
  * Calculated reserves for group endowment, term and premium back policies which was a vital part of the final valuation report.
  * Liaised directly with the consulting actuary and provided all sorts of technical and documental supports during actuarial valuation
  * Supervisor: Md. Salahuddin Soud, VP
  
## Skills

* Language
  - Bengali: Native
  - English: Fluent 
* Computer Literacy
  * Programming Languages: Python, FORTRAN, Julia, R, MATLAB, Mathematica
  * Software Development Tools: Git, GitHub, PyPi
* Musical Instrument: Amateur/Novice Bamboo flute player

## Publications

- <a href="/research/holmc/index.qmd" target="_blank" style="text-decoration:none">High-Order Langevin Monte Carlo Algorithms</a>  
  Dang, Thanh; Mert, Gurbuzbalaban; Islam, Mohammad Rafiqul; Zhu, Lingjiong  (2025) "High-Order Langevin Monte Carlo Algorithms." *arXiv preprint arXiv.2508.17545*

- <a href="/research/extrasgld/index.qmd" target="_blank" style="text-decoration:none">Generalized EXTRA stochastic gradient Langevin dynamics</a>  
  Mert, Gurbuzbalaban; Islam, Mohammad Rafiqul; Wang, Xiaoyu; Zhu, Lingjiong  (2024) "Generalized EXTRA stochastic gradient Langevin dynamics." *arXiv preprint arXiv.2412.01993*  
- <a href="/publication/pub2/index.qmd" target="_blank" style="text-decoration:none">GJR-GARCH Volatility Modeling under NIG and ANN for Predicting Top Cryptocurrencies </a>  
  Mostafa, F; Saha, P; Islam, Mohammad R.; Nguyen, N. (2020) "GJR-GARCH Volatility Modeling under NIG and ANN for Predicting Top Cryptocurrencies." *Journal of Risk and Financial Management*.
- <a href="/publication/pub1/index.qmd" style="text-decoration:none">Comparison of Financial Models for Stock Price Prediction </a>  
  Islam, Mohammad R.; Nguyen, N. (2020) "Comparison of financial models for stock price prediction." *Journal of Risk and Financial Management*. 

  
## Talks and Presentations  

- <a href="/talks/2026-03-03-icerm.qmd" style="text-decoration:none"> Generalized EXTRA SGLD: Eliminating Network Bias in Decentralized Bayesian Learning</a>  
  March 03, 2026  
  Poster Presentation at Institute for Computational and Experimental Research in Mathematics (ICERM), Brown University, Providence, Rhode Island   
- <a href="/talks/2026-01-30-gradseminar.qmd" style="text-decoration:none"> High-Order and Bias-Free Distributed Langevin Dynamics for Scalable Bayesian Inference </a>  
  January 30, 2026  
  Presentation at Department of Mathematics, Florida State University, Tallahassee, Florida
- <a href="/talks/2023-11-20-candi.qmd" style="text-decoration:none"> The Heavy-Tail Phenomenon in Decentralized Stochastic Gradient Descent</a>  
  November 20, 2023  
  Presentation at James J Love Building, Florida State University, Tallahassee, Florida  
- <a href="/talks/2023-10-05-st-op.qmd" style="text-decoration:none"> Decentralized Stochastic Gradient Langevin Dynamics and Hamiltonian Monte Carlo</a>  
  October 05, 2023  
  Presentation at James J Love Building, Florida State University, Tallahassee, Florida  
- <a href="/talks/2020-04-26-project.qmd" style="text-decoration:none"> Sensitivity analysis for Monte Carlo and Quasi Monte Carlo option pricing</a>  
  April 28, 2020  
  Presentation at Cafaro Hall, Youngstown State University, Youngstown, Ohio  
  
## Teaching

  - <a href="/teaching/sp26.qmd" style="text-decoration:none"> Spring 2026: MAC2311 Calculus and Analytic Geometry II</a>
  - <a href="/teaching/fa25.qmd" style="text-decoration:none"> Fall 2025: MAC2311 Calculus and Analytic Geometry II</a>
  - <a href="/teaching/sp25.qmd" style="text-decoration:none"> Spring 2025: MAC2311 Calculus and Analytic Geometry I</a> 
  - <a href="/teaching/sp24.qmd" style="text-decoration:none"> Spring 2024: MAP4170 Introduction to Actuarial Mathematics</a>  
  - <a href="/teaching/sp23.qmd" style="text-decoration:none"> Fall 2023: MAP4170 Introduction to Actuarial Mathematics</a>  
  - <a href="/teaching/fall23.qmd" style="text-decoration:none"> Spring 2023: MAC1140 PreCalculus Algebra</a>  
  - <a href="/teaching/fall22.qmd" style="text-decoration:none"> Fall 2022: MAC2311 Calculus and Analytic Geometry I</a>  
  - <a href="/teaching/fall21.qmd" style="text-decoration:none"> Fall 2021 and Spring 2022: PreCalculus and Algebra</a>  
  - <a href="/teaching/f18-f21.qmd" style="text-decoration:none"> Fall 2018 to Spring 2020: College Algebra, Trigonometry</a>  
  

## Funding, Awards & Scholarships

* **[2026]** AMS Spring Eastern Sectional Meeting Graduate Student Travel Grant ($400.00)
* **[2026]** Florida State Undergraduate Research Opportunity Program (UROP) Mentorship Fund for the 2025-2026 Academic Year ($490.10)
* **[2026]** The Institute for Computational and Experimental Research in Mathematics (ICERM) Workshop Grant ($967.44)
* **[2026]** Florida State Mathematics Department Travel Grant ($400.00)
* **[2026]** Student Government Association (SGA)-Congress of Graduate Students (COGS) Conference Presentation and Attendance Grants ($350.00)
* **[2024]** Bettye Anne Busbee Case Graduate Fellowship & Doctoral Mentorship Recognition 2024 ($1000.00)
* **[2020]** Outstanding Graduate Student in Statistics Award for the 2019-2020 academic year ($150.00)
* **[2019]** Society of Actuaries (SOA) travel grant to attend 6th Annual Midwest Actuarial Student Conference, University of Wisconsin, Milwaukee, WI ($125.00)
* **[2018]** Graduate College Premiere Scholarship, Youngstown State University
* **[2015]** MetLife Bangladesh Actuarial Study Program 2015 Fellowship

***

## Memberships

1. [Bangladesh Mathematical Society](https://www.bdmathsociety.org/){target="_blank" style="text-decoration:none"}: **Life Member**
2. [Society of Actuaries (SOA), USA](https://www.soa.org){target="_blank" style="text-decoration:none"}: **Student Member**
3. [Society for Industrial and Applied Mathematics (SIAM), USA](https://www.siam.org/){target="_blank" style="text-decoration:none"}: **Student Member**
4. [American Mathematical Society (AMS)](https://www.ams.org){target="_blank" style="text-decoration:none"}: **Student Member**
5. Graduate Student Council: FSU Mathematics Department