---
listing: 
  - id: phdrs
    contents: "/research/"
    type: grid
    grid-columns: 2
    grid-item-align: center
    image-lazy-loading: true
    fields: [title, image, author,date]
    sort: "date desc"
  - id: tandp
    contents: "/talks/"
    type: table
    sort: "date desc"
    filter-ui: false
    sort-ui: false
    fields: [date,title]
---  

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>  

<p style="text-align: justify">  
  My research focuses on *Theoretical Machine Learning*, particularly stochastic optimization and sampling techniques in Bayesian learning using Markov-Chain Monte Carlo (MCMC) algorithms. I work on developing scalable algorithms for collaborative learning under regularization and privacy constraints.
</p>

## Current Research  

::: {#phdrs}
:::

## Publications  

### Preprints 

- <a href="/research/dpsgld/index.qmd" target="_blank" style="text-decoration:none">Decentralized Proximal Stochastic Gradient Langevin Dynamics</a>  
  Islam, Mohammad Rafiqul; Zhu, Lingjiong  (2026) "Decentralized Proximal Stochastic Gradient Langevin Dynamics." *<a href="https://arxiv.org/abs/2605.00723" target="_blank" style="text-decoration:none">arXiv preprint arXiv.2605.00723</a>*

- <a href="/research/holmc/index.qmd" target="_blank" style="text-decoration:none">High-Order Langevin Monte Carlo Algorithms</a>  
  Dang, Thanh; Mert, Gurbuzbalaban; Islam, Mohammad Rafiqul; Zhu, Lingjiong  (2025) "High-Order Langevin Monte Carlo Algorithms." *<a href="https://arxiv.org/abs/2508.17545" target="_blank" style="text-decoration:none">arXiv preprint arXiv.2508.17545</a>*

- <a href="/research/extrasgld/index.qmd" target="_blank" style="text-decoration:none">Generalized EXTRA stochastic gradient Langevin dynamics</a>  
  Mert, Gurbuzbalaban; Islam, Mohammad Rafiqul; Wang, Xiaoyu; Zhu, Lingjiong  (2024) "Generalized EXTRA stochastic gradient Langevin dynamics." *<a href="https://arxiv.org/abs/2412.01993" target="_blank" style="text-decoration:none">arXiv preprint arXiv.2412.01993</a>*  

### Peer-Reviewed Publications  

- <a href="/publication/pub2/index.qmd" target="_blank" style="text-decoration:none">GJR-GARCH Volatility Modeling under NIG and ANN for Predicting Top Cryptocurrencies </a>  
  Mostafa, F; Saha, P; Islam, Mohammad R.; Nguyen, N. (2020) "GJR-GARCH Volatility Modeling under NIG and ANN for Predicting Top Cryptocurrencies." *Journal of Risk and Financial Management*.
- <a href="/publication/pub1/index.qmd" target="_blank" style="text-decoration:none">Comparison of Financial Models for Stock Price Prediction </a>  
  Islam, Mohammad R.; Nguyen, N. (2020) "Comparison of financial models for stock price prediction." *Journal of Risk and Financial Management*. 

## Undergraduate Research Mentorship  

### FSU Mathematics Directed Reading Program (DRP) 2024-2025  

<p style="text-align: justify"> 
<a href="https://fsumathdrp.wixsite.com/fsumathdrp" target="_blank" style="text-decoration:none"> Directed Reading Program (DRP) </a> is a research mentorship program for undergraduate students at Florida State University. The program provides an opportunity for students to work closely with graduate students on research projects in mathematics and related fields. The following students have been mentored by me in the DRP program:</p>  

- <a href="https://www.linkedin.com/in/lily-g-kinney/" target="_blank" style="text-decoration:none">Lily Kinney</a>   
- <a href="https://www.linkedin.com/in/kieraagic/" target="_blank" style="text-decoration:none">Kiera Agic</a>  

**Project:** Comparative study of predictive models in Machine Learning  

### Undergraduate Research Opportunity Program (UROP) 2025-2026  

<p style="text-align: justify">
<a href="https://cre.fsu.edu" target="_blank" style="text-decoration:none"> Center for Undergraduate Research and Academic Engagement (CRE) </a> is a research mentorship program for undergraduate students at Florida State University. The program provides an opportunity for students to work closely with faculty members, postdocs, and graduate students on research projects in various fields. The following students have been mentored by me in the UROP program:</p>

- <a href="https://www.linkedin.com/in/sarah-thapa-4aa751318/" target="_blank" style="text-decoration:none">Sarah Thapa</a>  

**Project:** Using Machine Learning to Identify Factors Contributing to Higher Fatalities in Florida Traffic Crashes.   

- <a href="https://www.linkedin.com/in/aiden-marin/" target="_blank" style="text-decoration:none">Aiden Marin</a>  
 
**Project:** Comparing Machine Learning Models with the Black-Scholes-Merton Model for Option Pricing.

## Course Projects  
- <a href="https://www.academia.edu/103433771/Option_pricing_techniques_A_performance_based_comparative_study_of_the_randomized_quasi_Monte_Carlo_method_and_Fourier_cosine_method" target="_blank" style="text-decoration:none">Option pricing techniques: A performance-based comparative study of the randomized quasi-Monte Carlo method and Fourier cosine method</a>  
  Advisor: <a href="https://www.math.fsu.edu/~okten/" target="_blank" style="text-decoration:none">Prof. Giray Ökten</a>
  
  <div style="text-align:justify">
    Pricing financial derivatives such as options with desired accuracy can be hard due to the nature of the functions and complicated integrals required by the pricing techniques. In this paper we investigate the pricing methodology of the European style options using two advanced numerical methods, namely, Quasi-Monte Carlo and Fourier Cosine (COS). For the RQMC method, we use the random-start Halton sequence. We use the Black-Scholes-Merton model to measure the pricing quality of both of the methods. For the numerical results we compute the option price of the call option and we found a few reasons to prefer the RQMC method over the COS method to approximate the European style options.
  </div>  
  
- <a href="https://www.academia.edu/13322836/Study_of_Runge_Kutta_Method_of_Higher_orders_and_its_Applications" target="_blank" style="text-decoration:none">Study of Runge-Kutta Method of Higher orders and its Applications</a>  
  Advisor: <a href="http://appliedmath.du.ac.bd/details-ofdr-md-abdus-samad/" target="_blank" style="text-decoration:none">Dr. Md. Abdus Samad </a>

  <div style="text-align: justify">
    This project is concerned with the study on Runge-Kutta method to apply on different order of differential equation and solve different types of problem such as initial value problem and boundary value problem in ordinary differential equation. At first we discuss about the definition and generation of differential equation specially based on partial differential equation and then definition of Runge-kutta method and the derivation of midpoint method and the formula of Runge-Kutta metod of fourth order and sixth order. We also write FORTRAN 90/95 program for different order of Runge-Kutta methods. We have solved some examples of fourth order R-K method and sixth order R-K method to get the application of R-K method. We also compared the solution of R-K method with exact solution for different step sizes. Then we have given simultaneous first order differential equation and second order differential equation and then solved them by fourth order Runge-Kutta method. At last we have discussed the boundary value problem which we have solved by fourth and sixth order R-K method. After that we have written the algorithm of shooting method and showed computer results with the difference between two answer along with percentages of error.
  </div>


## Talks and Presentations  


